### ISSUE TITLE
Cant get it to work - error in skills

### ISSUE THREAD

**Issue by andlo** [snipsco/snipsskills#20]
No matter how I try I dont get this working.

Snips seems to work - installed on RPI3 whith apt-get.

The fake weather or the OWM seems not working...But maybe it is not the skills but the snipsmanager?

Nov 19 12:56:36 snips snipsmanager[591]: Exception in thread Thread-16:
Nov 19 12:56:36 snips snipsmanager[591]: Traceback (most recent call last):
Nov 19 12:56:36 snips snipsmanager[591]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Nov 19 12:56:36 snips snipsmanager[591]:     self.run()
Nov 19 12:56:36 snips snipsmanager[591]:   File "/usr/lib/python2.7/threading.py", line 754, in run
Nov 19 12:56:36 snips snipsmanager[591]:     self.__target(*self.__args, **self.__kwargs)
Nov 19 12:56:36 snips snipsmanager[591]:   File "/opt/venvs/snipsmanager/local/lib/python2.7/site-packages/snipsmanager/commands/run.py", line 145, in handle_intent
Nov 19 12:56:36 snips snipsmanager[591]:     intent_def = skilldef.find_wildcard(intent)
Nov 19 12:56:36 snips snipsmanager[591]: TypeError: find_wildcard() takes exactly 1 argument (2 given)
Nov 19 12:56:36 snips snips-analytics[520]: INFO:snips_analytics_hermes: Cleanup
Nov 19 12:56:36 snips snips-analytics[520]: INFO:snips_analytics_hermes: Idle
Nov 19 12:56:42 snips snips-dialogue[530]: INFO:snips_dialogue_lib::coordinator::coordinator: Session [2da85946-7443-46c2-9c96-cf248acd01fe]: closing session which was active: Timeout
Nov 19 12:56:42 snips snips-dialogue[530]: INFO:snips_dialogue_lib::coordinator::coordinator: Site [default]: reset site -> turn off ASR and turn on Hotword
N

**Comment by anthonyray** [comment]
Closing the issue as SnipsManager is deprecated.
