### ISSUE TITLE
[Enhancement] Update documentation and add git 

### ISSUE THREAD

**Issue by psychonetic** [snipsco/snipsskills#26]
Hello,

maybe for you and me it's obvious to have git installed if we use for example
 `url: https://github.com/snipsco/snips-skill-hue`
in our snipsfile, but if you don't have git installed you will get an error, which is not obvious: "please make sure you have the right permissions and the module exists".

It would be great if you could add git as a dependency (escpecially for raspberry pi installations) and  instead of that squishy error something like "git is not installed".

**Comment by anthonyray** [comment]
Thanks ! 
We added git as a dependency in the documentation !
