### ISSUE TITLE
Asound.conf Permission Denied

### ISSUE THREAD

**Issue by todschmidt** [snipsco/snipsskills#33]
Installing as Pi gives this error
```
⋯ Copying asound configuration to /etc/asound.conf
↯ [Errno 13] Permission denied: '/etc/asound.conf'
```
Should prompt for sudo pass as it does in another spot

**Comment by anthonyray** [comment]
Correct ! We will fix this ! 
In the meantime, you can run the command : `sudo snipsmanager install`. 

✌🏾
