### ISSUE TITLE
incorrect .acoundrc / asound.conf for Jabra 410 (510 too?)

### ISSUE THREAD

**Issue by frollic** [snipsco/snipsskills#38]
the recommended asound.conf / .ascoundrc for Jabra doesn't
work for Jabra 410 (and perhaps 510 as well). 
The result is Snips speeking too fast.

The asoundrc / asound.conf below works:
https://github.com/wzpan/dingdang-robot/issues/114

**Comment by todschmidt** [comment]
FWIW, I had to manually add rate 48000 under the playback section in the asound.conf to get it to work

**Comment by Clingo77** [comment]
Hello,
I've spent several hours trying to resolve that issue with my Jabra410 speaking too fast with SNIPS and I'm running in circle :(
I was intersted by comment from tschmidty69 saying "FWIW, I had to manually add rate 48000 under the playback section in the asound.conf to get it to work"  but I'm not able to put that rate 48000 in my asound.conf as I'm always getting error message.

Would it be possible to get a copy of  working files (asound.conf and .asoundrc
) ?

Thanks

**Comment by todschmidt** [comment]
Check out this post for a jabra conf that works for me.

<http://goneridin.blogspot.com/>
